<?php 
session_start();
include 'process.php'; 
?>
<hr>
<p style="text-align: justify;">Le presenti condizioni di utilizzo (“Condizioni d'uso”) si applicano ai siti web di proprietà <?php echo $_SESSION["nome"]; ?> (d'ora in poi Azienda), pubblicati all'indirizzo <?php echo $_SESSION["sito"]; ?>.</p>
<p style="text-align: justify;"><strong>Utilizzando il sito, l'utente accetta le presenti condizioni d'uso; qualora non accetti, l'utente deve astenersi dall'utilizzare il sito.</strong></p>
<p style="text-align: justify;">L'Azienda si riserva il diritto di cambiare, modificare, aggiungere o rimuovere clausole delle presenti Condizioni d'uso a propria discrezione e in qualsiasi momento. L'utente è tenuto a consultare periodicamente le Condizioni d'uso per verificare eventuali cambiamenti. L'utilizzo del sito in seguito alla pubblicazione di modifiche costituirà l'accettazione di tali modifiche da parte dell'utente. Fermo restando il rispetto delle presenti Condizioni d'uso, l'Azienda concede all'utente il diritto personale, non esclusivo, non trasferibile e limitato, di accedere al sito e utilizzarlo.</p>
<p style="text-align: justify;"><strong>Ulteriori termini e condizioni per prodotti e servizi</strong><br />L'acquisto di prodotti o la fornitura di servizi prevedono ulteriori termini e condizioni applicabili, le quali devono intendersi integrate nelle presenti Condizioni d'uso.</p>
<p style="text-align: justify;">L'utente accetta di rispettare tali ulteriori termini e condizioni aggiuntivi, dichiarando altresì, dove richiesto, di aver raggiunto l'età legale necessaria per utilizzare e/o partecipare a tali servizi o funzionalità.</p>
<p style="text-align: justify;">Gli obblighi dell'Azienda in relazione ai propri prodotti e servizi sono regolati esclusivamente dai contratti in base ai quali tali prodotti e servizi vengono forniti, e nessuna parte di questo Sito può essere interpretata come una modifica dei suddetti contratti.</p>
<p style="text-align: justify;">L'Azienda si riserva il diritto di modificare qualsiasi prodotto o servizio menzionato sul sito nonché i prezzi relativi ai prodotti e servizi, in qualsiasi momento e senza alcun preavviso.</p>
<p style="text-align: justify;">Il materiale relativo a prodotti o servizi pubblicato sul sito potrebbe includere informazioni obsolete; l'Azienda non è tenuta a correggere tale materiale e non ha alcuna responsabilità in merito.</p>
<p style="text-align: justify;"><strong>Contenuti sul sito</strong><br />Ogni testo, grafica, interfaccia utente, interfaccia visiva, fotografia, marchio commerciale, logo, suono, musica, illustrazione e codice informatico o altri materiali (collettivamente, “Contenuti”) presenti sul sito, inclusi senza alcuna limitazione il design, la struttura, la selezione, il coordinamento, l'espressione, l'aspetto e la disposizione di tali Contenuti, appartengono a o sono controllati o concessi in licenza dall'Azienda e sono protetti dalle leggi in materia del diritto d'autore, brevetti, segni distintivi e marchi commerciali, nonché dalle normative sui diritti di proprietà intellettuale e sulla concorrenza sleale.</p>
<p style="text-align: justify;">E' quindi vietato copiare, riprodurre, pubblicare, caricare, visualizzare pubblicamente, codificare, tradurre, trasmettere o distribuire qualsiasi parte del sito e dei relativi Contenuti su qualsiasi computer, server, sito web o altro mezzo destinato alla pubblicazione, alla distribuzione o a qualsiasi finalità commerciale senza previo consenso scritto da parte dell'Azienda.</p>
<p style="text-align: justify;">L'utente potrà utilizzare le informazioni rese intenzionalmente disponibili dall'Azienda a patto che si astenga dal copiare o pubblicare le informazioni su qualsiasi computer in rete o dal trasmettere le stesse con qualsiasi mezzo, non alteri in alcun modo le informazioni e non rilasci alcun tipo di dichiarazione o garanzia aggiuntiva relativamente a tali documenti e informazioni.</p>
<p style="text-align: justify;"><strong>Uso del sito da parte dell'utente</strong><br />Non è consentito utilizzare tecniche, dispositivi, programmi, metodologie o algoritmi automatici, né processi manuali per accedere, acquisire, copiare o monitorare qualsiasi parte del sito o dei Contenuti; è altresì vietato riprodurre o aggirare in alcun modo la struttura di navigazione o la presentazione del sito o dei Contenuti per ottenere o tentare di ottenere materiali, documenti o informazioni con mezzi non resi intenzionalmente disponibili sul sito.</p>
<p style="text-align: justify;">Nei suddetti casi l'Azienda si riserva il diritto di bloccare tali attività illecite.</p>
<p style="text-align: justify;">L'utente deve astenersi dal cercare di ottenere l'accesso non autorizzato a qualsiasi parte o funzionalità del sito, o ad altri sistemi o reti collegate al sito o a qualsiasi server dell'Azienda, come pure ai servizi offerti su o attraverso il sito, mediante tecniche di hacking, intercettazione delle password o qualsiasi altro mezzo illegale.</p>
<p style="text-align: justify;">L'utente accetta di astenersi dal compiere azioni che provochino un carico di lavoro irragionevole o sproporzionato sull'infrastruttura del sito o i sistemi e le reti dell'Azienda, o sui sistemi e le reti collegati al sito o all'Azienda.</p>
<p style="text-align: justify;">È vietato sondare, esaminare o testare la vulnerabilità del sito o di qualsiasi rete a esso collegata, nonché di violarne la sicurezza o le misure di autenticazione. E' altresì vietato tracciare o cercare di tracciare l'origine di informazioni relative a qualsiasi utente o visitatore del sito, o qualsiasi cliente dell'Azienda, inclusi gli account dell'Azienda appartenenti a terzi.</p>
<p style="text-align: justify;">L'utente accetta di non utilizzare alcun tipo di dispositivo o software per interferire o tentare di interferire con il corretto funzionamento del sito o di qualsiasi transazione condotta sullo stesso, nonché con l'utilizzo del sito da parte di terzi.</p>
<p style="text-align: justify;">È vietato fingere di essere o di rappresentare altre persone nonché impersonare altri individui o entità.</p>
<p style="text-align: justify;">L'utente accetta di non utilizzare il sito o i relativi Contenuti per attività proibite dalla legge o dalle presenti Condizioni d'uso, nonché di astenersi dal sollecitare lo svolgimento di qualsiasi attività illegale o in violazione dei diritti dell'Azienda o di altri.</p>
<p style="text-align: justify;">L'utente è l'unico e personale responsabile dell'utilizzo del servizio, nonché delle eventuali conseguenze pregiudizievoli che dovessero ricadere sulla Azienda e sui terzi, e ciò con riferimento alla vigente normativa italiana in materia civile e penale e, per quanto applicabile, alla normativa straniera.</p>
<p style="text-align: justify;">L'utente si obbliga a:</p>
<ol style="list-style-type: lower-alpha; text-align: justify;">
	<li>non interferire, destabilizzare od interrompere il servizio, i server o i network collegati con il servizio, non agire in contrasto con qualsivoglia requisito, procedura o regola del servizio;</li>
	<li>non usare il servizio per scopi illegali ovvero contro l'ordine pubblico, il buon costume e la morale;</li>
	<li>non usare il servizio per trasmettere o diffondere (anche mediante link) materiale illecito, pornografico, razzista, lesivo della privacy e/o comunque osceno, volgare (anche se orientato ad un pubblico adulto e caratterizzato da nudità o atti di natura sessuale), diffamatorio, calunnioso, abusivo o comunque inviare informazioni private relative ad una persona senza il suo consenso, infliggendo intenzionalmente stress emotivo;</li>
	<li>non trasmettere materiale e/o messaggi che incoraggino terzi a mettere in atto una condotta illecita e/o criminosa passibile di responsabilità penale o civile;</li>
	<li>osservare, e far osservare ad eventuali soggetti che utilizzino il servizio, tutti i regolamenti, direttive e procedure di rete connesse al servizio medesimo;</li>
	<li>non creare intestazioni o in altro modo manipolare segni distintivi o indicazioni al fine di contraffare l'origine di un contenuto del servizio o il servizio stesso;</li>
	<li>non utilizzare o diffondere il contenuto del servizio che comporti la violazione di brevetti, marchi, segreti, diritti d'autore o altri diritti di proprietà industriale e/o intellettuale del fornitore o di terzi soggetti;</li>
	<li>non inviare messaggi commerciali e/o promozionali ovvero non porre in essere attività di «spam», «catene di S. Antonio» nonché qualsiasi altra forma di sollecitazione non autorizzata nei confronti di gruppi di discussione, social forum e qualsiasi altra forma di comunicazione/aggregazione, anche ”crossposting” e/o indirizzi di utenti che non abbiano alcun rapporto con il mittente; in particolare di non inviare pubblicità non richiesta via e-mail e/o mailbombing (spedire numerosi messaggi senza significativi cambiamenti nel contenuto allo stesso utente), iscrivere qualcuno a una mailing list senza il permesso della persona stessa, tentare senza autorizzazione di entrare in un computer dotato di sistema di sicurezza;</li>
	<li>diffondere virus o qualsiasi altra tecnologia volta a danneggiar il sito o gli altri utenti del sito internet;</li>
	<li>non divulgare a terze informazioni in relazione ai sistemi e alle modalità di accesso al servizio.</li>
</ol>
<p style="text-align: justify;">È comunque espressamente vietato utilizzare il servizio per contravvenire in modo diretto e/o indiretto alle vigenti leggi dello Stato italiano ovvero di altro Stato estero.</p>
<p style="text-align: justify;">L'utente potrà trasferire le informazioni rese dal servizio ad altri elaboratori esclusivamente per uso personale e comunque all'interno della propria struttura aziendale.</p>
<p style="text-align: justify;">L'utente conviene e concorda che il trattamento tecnico, la trasmissione o la diffusione del servizio, inclusi i suoi contenuti, possa comprendere la trasmissione o diffusione dei contenuti tramite altri network e la necessità della Azienda o dei terzi fornitori di quest'ultima di apportare modifiche al servizio al fine di conformarlo o adattarlo alle specifiche tecniche, agli standard di collegamento dei propri network ovvero alle apparecchiature ed ai programmi di connessione.</p>
<p style="text-align: justify;">L'Azienda si riserva la facoltà di interrompere l'accesso al sito web, anche nei confronti di un solo utente, nel caso in cui ritenga, a proprio insindacabile giudizio, che il sito sia utilizzato in contravvenzione dei punti sopra descritti.</p>
<p style="text-align: justify;"><strong>Account, password e sicurezza</strong><br />Il sito offre alcuni servizi e funzionalità le quali richiedono, obbligatoriamente, l'apertura di un account con relativa UserID e password. L'utente è responsabile in via esclusiva della riservatezza dei dati del proprio account, inclusa la password, e di qualsiasi attività originante dall'account stesso e, conseguentemente, ne rimane il solo ed unico responsabile per tutti gli usi, siano essi dal medesimo autorizzati ovvero non autorizzati. L'utente si impegna a uscire dal proprio account al termine di ogni sessione di utilizzo del servizio.</p>
<p style="text-align: justify;">L'utente sarà il solo ed unico responsabile per la sicurezza e l'uso appropriato di tutti gli user name e password assegnatigli dall'Azienda, eventualmente anche per l'aggiornamento, la modificazione ed il monitoraggio delle informazioni diffuse on line. L'utente è tenuto, pertanto, ad adottare tutti i provvedimenti necessari per assicurare che siano mantenute segrete, utilizzate propriamente, non rivelate a soggetti non autorizzati.</p>
<p style="text-align: justify;">L'utente si impegna a non cedere o divulgare (direttamente o indirettamente) a terzi sia la UserID sia la password personali e si impegna a comunicare immediatamente all'Azienda qualsiasi eventuale furto e/o smarrimento e/o uso non autorizzato o qualsiasi altra violazione alla sicurezza da parte di terzi della propria UserID e della propria password non appena avutane conoscenza.</p>
<p style="text-align: justify;">Tuttavia, l'utente potrebbe essere ritenuto responsabile degli eventuali danni causati all'Azienda o ad altri utenti o visitatori del Sito dall'utilizzo del proprio UserID, della password o dell'account da parte di terzi.</p>
<p style="text-align: justify;">Non è consentito utilizzare lo UserID, la password o l'account di un altro utente senza l'esplicito permesso e consenso del legittimo proprietario.</p>
<p style="text-align: justify;">L'Azienda pertanto non sarà in alcun modo responsabile di eventuali perdite o danni provocati dal mancato rispetto di tali obblighi da parte dell'utente, il quale si impegna sin d'ora a manlevare e tenere indenne l'Azienda da ogni e qualsiasi richiesta, anche di risarcimento danni, proposta e/o derivante, direttamente ovvero indirettamente, dal sopra indicato uso od abuso del servizio e/o dell'account.</p>
<p style="text-align: justify;"><strong>Privacy</strong><br />Il sito è regolato dalla Politica di tutela della privacy dell'Azienda, i cui termini sono parte integrante delle presenti Condizioni d'uso.</p>
<p style="text-align: justify;">L'utente prende atto ed accetta che le trasmissioni via internet non sono mai completamente riservate o sicure. L'utente riconosce che qualsiasi dato o messaggio inviato al Sito potrebbe essere letto o intercettato da terzi, anche in presenza di uno speciale avviso che una determinata trasmissione (ad esempio l'invio dei dati della carta di credito) è codificata.</p>
<p style="text-align: justify;">Il documento di privacy è disponibile al seguente indirizzo web <span style="color: #ff0000;">(VERIFICARE URL)</span>: <?php echo $_SESSION["sito"]; ?><a href="../privacy.html">/</a>privacy.html.</p>
<p style="text-align: justify;">L'Azienda potrà divulgare le informazioni relative all'utente (inclusa la sua identità) qualora determini che tale divulgazione è necessaria in relazione a eventuali indagini o reclami riguardanti l'utilizzo del sito da parte dell'utente, o per identificare, contattare o intentare azioni legali contro persone che possono ledere o interferire con (in modo intenzionale o meno) i diritti e i diritti di proprietà di dell'Azienda o di visitatori o utenti del sito, inclusi i clienti dell'Azienda. L'Azienda si riserva il diritto di divulgare in qualsiasi momento qualunque informazione risulti necessaria per adempiere a leggi, normative, processi legali o richieste governative. L'Azienda potrebbe anche divulgare le informazioni dell'utente nel caso in cui determini che la legge vigente richiede o permette tale divulgazione, incluso lo scambio di informazioni con altre Azienda e organizzazioni per finalità di protezione dalle frodi.</p>
<p style="text-align: justify;">L'Azienda potrà conservare qualsiasi trasmissione o comunicazione intercorsa tra l'utente e l'Azienda tramite il sito o qualsiasi servizio offerto su o attraverso il sito, e potrà inoltre divulgare tali dati se richiesto dalla legge o nel caso in cui determini che tale conservazione o divulgazione è ragionevolmente necessaria per rispettare processi legali, esercitare le presenti Condizioni d'uso, rispondere alla pretesa che i contenuti di qualsivoglia comunicazione violino i diritti di terzi oppure proteggere i diritti, i diritti di proprietà o la sicurezza personale dell'Azienda, i suoi dipendenti, gli utenti o i visitatori del sito e il pubblico e, in generale, esercitare un diritto o le difese di un diritto in sede giudiziaria.</p>
<p style="text-align: justify;"><strong>Regole generali di utilizzo del servizio</strong><br />L'utente si obbliga a tenere indenne la Azienda ed i suoi dipendenti e consulenti, da ogni e qualsivoglia pregiudizio e danno da essi subito, da ogni responsabilità, da costi, spese (anche legali) da essi sostenute, nonché a manlevarli da ogni eventuale azione, ragione, pretesa avanzata da terzi che trovino causa o motivo in comportamenti od omissioni riconducibili all'utente, oppure che siano conseguenza dell'inadempimento da parte dell'utente agli obblighi posti a suo carico dal regolamento contrattuale.</p>
<p style="text-align: justify;"><strong>Esclusione e limitazione di responsabilità</strong><br />L'Azienda non garantisce che il sito o i relativi contenuti, servizi o funzionalità siano privi di errori o disponibili in maniera continua, né che eventuali difetti verranno corretti o che l'utilizzo del sito da parte dell'utente comporti risultati specifici.</p>
<p style="text-align: justify;">Il sito e i suoi contenuti sono forniti “tali e quali” e secondo disponibilità; tutte le informazioni fornite sul sito sono soggette a modifica senza preavviso.</p>
<p style="text-align: justify;">L'Azienda non può garantire che eventuali documenti o altri dati scaricati dal sito siano privi di virus o contaminazioni o caratteristiche distruttive. L'Azienda esclude qualsiasi garanzia esplicita o implicita, incluse, ma non limitatamente ad esse, le garanzie di accuratezza, non violazione, commerciabilità e idoneità a soddisfare uno scopo specifico.</p>
<p style="text-align: justify;">L'Azienda declina qualsiasi responsabilità per atti, omissioni o comportamenti di terzi connessi o relativi all'utilizzo del sito e/o di qualsiasi servizio fornito dall'Azienda da parte dell'utente.</p>
<p style="text-align: justify;">L'utente si assume la piena responsabilità per l'utilizzo del sito e dei siti collegati. Nel caso in cui l'utente non sia soddisfatto del sito o dei relativi contenuti, avrà come unico rimedio la cessazione dell'utilizzo del sito o dei contenuti.</p>
<p style="text-align: justify;">La suddetta limitazione di responsabilità è parte integrante del contratto tra le parti e si applica a tutti gli eventuali danni, responsabilità e lesioni derivanti da malfunzionamento, errore, omissione, interruzione, cancellazione, difetto, ritardo di funzionamento o trasmissione, virus informatico, guasto alle linee di comunicazione, furto, distruzione o accesso, alterazione o utilizzo non autorizzato, sia esso causato da inadempienza, colpa, negligenza o altra causa.</p>
<p style="text-align: justify;">L'utente, in caso di interruzione del servizio per causa allo stesso addebitabile, non potrà richiedere all'Azienda il rimborso di alcuna somma, neanche parziale, per qualunque titolo e/o ragione.</p>
<p style="text-align: justify;">Fermo restando quanto indicato ai precedenti articoli, l'utente riconosce ed accetta che l'Azienda non potrà in alcun caso essere considerata responsabile - né a titolo contrattuale, né a titolo extracontrattuale - nei confronti dell'utente (ovvero di terzi) per qualsiasi tipo di danno diretto o indiretto ivi inclusi i danni relativi alla perdita di profitti, dell'avviamento commerciale o perdita di dati anche nel caso in cui l'Azienda sia stata avvertita (per iscritto o verbalmente) del possibile verificarsi di tali danni.</p>
<p style="text-align: justify;">A titolo esemplificativo e non tassativo l'Azienda non sarà responsabile di danni connessi o derivanti:</p>
<ol style="list-style-type: lower-alpha; text-align: justify;">
	<li>dall'uso, dal cattivo uso ovvero dalla impossibilità di utilizzare il servizio imputabili all'utente;</li>
	<li>dal costo di servizi sostitutivi rispetto al prodotto/servizio acquistato;</li>
	<li>dall'eventuale modifica, sospensione ovvero interruzione del servizio;</li>
	<li>dall'accesso non autorizzato ovvero da alterazione di trasmissioni e/o dati dell'utente, ivi incluso tra l'altro l'eventuale danno, anche economico, dallo stesso utente eventualmente subito per mancato profitto, uso, perdita di dati o di altri elementi intangibili.</li>
</ol>
<p style="text-align: justify;">In ogni caso sono espressamente escluse tutte le garanzie esplicite od implicite nella misura in cui ciò non contrasti con le vigenti norme di legge e fatta salva la responsabilità per dolo o colpa grave dell'Azienda.</p>
<p style="text-align: justify;">È espressamente convenuto ed accettato dall'utente che l'Azienda non potrà in nessun caso essere ritenuta responsabile per omissioni o errori che possano essere contenuti nelle informazioni che su richiesta dell'utente sono state utilizzate per l'esecuzione o realizzazione del servizio.</p>
<p style="text-align: justify;">L'utente manleva sostanzialmente e processualmente l'Azienda mantenendola indenne da ogni perdita, danno, responsabilità, costo o spese, incluse anche le spese legali, derivanti da ogni violazione dei precedenti punti di questo articolo.</p>
<p style="text-align: justify;">La responsabilità dell'Azienda per qualunque titolo derivante da questo contratto o comunque dalla prestazione dei servizi, compresa ogni azione per vizi, inadempimento o insuccesso dell'azione riparatrice intrapresa, sarà limitata al solo dolo o colpa grave e non si estenderà ad eventuali danni che siano conseguenza indiretta, imprevedibile o comunque anomala del vizio o dell'inadempimento come, in via esemplificativa, mancato guadagno, oneri finanziari, costi di arresto dell'attività, costo di attrezzature o servizi sostitutivi, danni o spese derivanti da pretese di terzi nei confronti dell'utente.</p>
<p style="text-align: justify;">L'utente riconosce espressamente che le limitazioni o esclusioni di responsabilità previste nelle presenti condizioni d'uso sono state pattuite come condizioni essenziali per la prestazione dei servizi e, al di fuori di quanto espressamente convenuto, rinuncia, senza riserva, ad ulteriori o diverse ragioni o azioni riparatorie.</p>
<p style="text-align: justify;">Nel caso in cui, indipendentemente dalle altre clausole delle presenti Condizioni d'uso, l'Azienda venga riconosciuta responsabile nei confronti dell'utente di qualsiasi danno o perdita derivante o connesso all'utilizzo del sito o dei contenuti, la responsabilità dell'Azienda non potrà in alcun caso essere superiore all'importo totale versato dall'utente come iscrizione o onere per l'utilizzo di qualsiasi servizio o funzionalità nel corso dei tre mesi precedenti la data del reclamo iniziale presentato all'Azienda (escluse le spese di acquisto di prodotti o servizi).</p>
<p style="text-align: justify;">L'utente prende atto ed accetta espressamente che l'utilizzo del servizio e la diffusione e conservazione delle informazioni ottenute o concessi tramite il servizio è effettuata a proprio ed esclusivo rischio e che lo stesso utente è il solo ed esclusivo responsabile per ogni danno al proprio computer o per la perdita di dati derivante dall'aver utilizzato il servizio.</p>
<p style="text-align: justify;">L'utente dichiara di aver preso visione delle caratteristiche del servizio scelto.</p>
<p style="text-align: justify;">L'utente riconosce e conviene che l'Azienda non presti alcun tipo di garanzia, espressa ovvero implicita, di commerciabilità, di compatibilità o idoneità ad uno scopo particolare dell'utente o di terzi e, inoltre, non presta alcuna garanzia in merito al fatto che il servizio corrisponda ai requisiti ed alle esigenze dell'utente stesso.</p>
<p style="text-align: justify;">L'utente riconosce e conviene che l'Azienda non presta alcuna garanzia nei suoi confronti circa i risultati che possono essere ottenuti con l'uso del servizio, circa gli eventuali errori di software e hardware del servizio ovvero inerenti all'affidabilità di ogni informazione ottenuta dall'utente per il tramite del servizio.</p>
<p style="text-align: justify;">Pertanto l'Azienda non può essere ritenuta responsabile per qualsivoglia danno diretto e/o indiretto derivante dall'impiego del servizio ovvero dall'interruzione del funzionamento del servizio.</p>
<p style="text-align: justify;">L'Azienda non presta alcuna garanzia in merito ai prodotti, materiali, merci ovvero servizi venduti, acquistati o comunque ottenuti dall'utente mediante il sito web o il servizio ovvero a seguito di eventuali transazioni effettuate tramite il servizio stesso.</p>
<p style="text-align: justify;"><strong>Sospensione del servizio</strong><br />L'Azienda si riserva il diritto di limitare, sospendere e/o interrompere immediatamente, <strong>senza preventivo avviso</strong>, l'utilizzo e/o fornitura del servizio ovvero di disconnettere (temporaneamente o definitivamente) l'account dell'utente e ciò senza riconoscimento di alcun rimborso indennizzo e/o risarcimento, con conseguente successiva cancellazione dell'account dell'utente, qualora venisse a conoscenza ovvero determinasse, a suo esclusivo insindacabile giudizio, che l'utente abbia compiuto azioni che possano comportare problemi, responsabilità legali oppure abbia violato ovvero stia violando le prescrizioni delle presenti condizioni d'uso, nonché la normativa vigente (incluso il D.Lgs. n. 196/2003).</p>
<p style="text-align: justify;">L'Azienda si riserva altresì il diritto di limitare, sospendere e/o interrompere immediatamente, senza preventivo avviso, l'utilizzo e/o fornitura del servizio nonché l'accesso al sito o l'account dell'utente qualora venisse a conoscenza ovvero ritenesse, a suo esclusivo insindacabile giudizio, che si sia verificata ovvero si stia verificando una delle seguenti circostanze:</p>
<ol style="list-style-type: lower-alpha; text-align: justify;">
	<li>un utilizzo del servizio che determini una situazione di pericolo o instabilità del server tale da arrecare danni all'Azienda;</li>
	<li>un traffico anomalo ovvero tale da impedire la normale erogazione del servizio in favore di altri clienti;</li>
	<li>qualora la pubblica autorità o altri soggetti terzi comunichino all'Azienda, oppure essa stessa accerti, un uso illecito, improprio ovvero non conforme alle leggi sia nazionali che internazionali nonché alle regole della “netiquette” del servizio da parte dell'utente;</li>
	<li>qualora l'Azienda accerti un uso contrario alla morale o l'ordine pubblico ovvero con lo scopo di recare molestia alla quiete pubblica o privata, di recare offesa o danno diretto o indiretto a chiunque e di tentare di sorprendere comunque il segreto dei messaggi privati;</li>
	<li>accessi al sito web da parte di terzi non autorizzati o, comunque, di cd. attacchi hacker;</li>
	<li>manutenzione ordinaria e/o straordinaria del sito web o dei sistemi informatici o per forza maggiore.</li>
</ol>
<p style="text-align: justify;">L'Azienda si riserva inoltre il diritto di cancellare account non confermati o inattivi da molto tempo.</p>
<p style="text-align: justify;">L'Azienda valuterà, infine, il materiale ritenuto «dubbio» a suo insindacabile giudizio e, previa comunicazione all'utente per chiarimenti, deciderà in ordine alla sospensione del servizio.</p>
<p style="text-align: justify;">In ogni caso l'Azienda si riserva il diritto di intraprendere le seguenti azioni in qualsiasi momento e senza alcun preavviso: modificare, sospendere o interrompere la funzionalità o l'accesso al sito o a parti di esso, per qualsiasi motivo; modificare o cambiare il sito o parti di esso e ogni eventuale norma o condizione relativa al sito, e interrompere la funzionalità del sito o parti di esso qualora ciò si rendesse necessario per eseguire operazioni di manutenzione ordinaria o straordinaria, correggere errori o apportare altre modifiche.</p>
<p style="text-align: justify;"><strong>Forza maggiore</strong><br />L'utente conviene e concorda che l'Azienda non potrà in nessun caso essere considerata responsabile nei confronti dell'utente ovvero di terzi per il ritardo o il mancato adempimento dei propri obblighi dovuti a caso fortuito o forza maggiore quali, a mero titolo esemplificativo e non tassativo, azioni di autorità pubbliche, alluvioni, incendi, furti, esplosioni, incidenti, scioperi e serrate anche non aziendali, atti di guerra, embargo, impossibilità di trasporto, sospensioni o problemi di telecomunicazione, fulmini, guasti agli impianti non imputabili all'Azienda, interruzioni o sovraccarico dei flussi energetici, guasti o interruzione delle linee telefoniche e/o informatiche anche non riconducibili all'attività del gestore (o concessionario) delle linee medesime, nonché interruzioni o sospensioni non imputabili o comunque indipendenti dalla volontà della Azienda ovvero derivanti da soggetti terzi fornitori dell'Azienda stessa.</p>
<p style="text-align: justify;"><strong>Clausola di manleva</strong><br />L'Azienda, i suoi dipendenti e amministratori, agenti e dirigenti non potranno in alcun modo essere ritenuti responsabili per eventuali danni provocati dall'utente e derivanti da violazioni delle prescrizioni di cui alle presenti Condizioni d'Uso.</p>
<p style="text-align: justify;">L'utente si impegna comunque a manlevare e mantenere integralmente indenne l'Azienda nonché i soggetti ad essa collegati o controllati, i suoi rappresentanti, dipendenti o ausiliari da qualsiasi responsabilità civile e penale derivante dall'utilizzo del sito, anche se causato da terzi attraverso l'account dell'utente.</p>
<p style="text-align: justify;"><strong>Legge applicabile e Giurisdizione</strong><br />Ogni questione inerente l'accesso o l'utilizzo del Sito, inclusa ogni eventuale controversia, sarà regolata dalle leggi italiane e sarà sottoposta in via esclusiva alla giurisdizione italiana, foro di Bologna.</p>
<p style="text-align: justify;"><strong>Varie</strong><br />Nel caso in cui una o più clausole delle presenti Condizioni d'uso siano ritenute nulle o inapplicabili, esse saranno limitate o eliminate nel grado minimo necessario e sostituite con una clausola valida che meglio esprima le intenzioni delle presenti Condizioni d'uso, in modo che le stesse restino pienamente valide e applicabili.</p>
<p style="text-align: justify;">Le presenti Condizioni d'uso rappresentano l'intero accordo tra le parti in merito all'utilizzo del sito e sostituiscono tutti i precedenti accordi stipulati in forma scritta o orale dalle parti in merito all'oggetto in questione. La mancata rivendicazione o richiesta di applicazione da parte dell'Azienda di qualsiasi clausola non rappresenterà una rinuncia a tale clausola o al diritto di far valere le presenti Condizioni d'uso; inoltre, l'eventuale condotta tra l'Azienda e l'utente o parti terze non potrà in alcun modo modificare le clausole delle Condizioni d'uso.</p>