<?php 
session_start();
include 'process.php'; 
?>
<hr>
<p style="text-align: justify;">In questa pagina si descrivono le modalità di gestione del sito in riferimento al trattamento dei dati personali degli utenti che lo consultano. Si tratta di un’informativa resa anche ai sensi del'art.13 del D.lgs 196/2003 e del Reg. UE 679/2016 a coloro che interagiscono con i servizi web accessibili per via telematica a partire dall’indirizzo: <?php echo $_SESSION["sito"]; ?>.</p>
<p style="text-align: justify;">L'informativa è resa solo per il sito in oggetto e non anche per altri siti Web eventualmente consultabili tramite i nostri links, di cui <strong><?php echo $_SESSION["nome"]; ?> </strong>non è in alcun modo responsabile.</p>
<p style="text-align: justify;"><strong>Il Titolare del trattamento</strong><br /> A seguito della consultazione di questo sito possono essere trattati dati relativi a persone identificate o identificabili. Il "Titolare" del loro trattamento è <strong><?php echo $_SESSION["nome"]; ?> <strong>nella persona del legale rappresentante pro-tempore </strong></strong><strong>che</strong> ha sede in <?php echo $_SESSION["indirizzo"]; ?>.</p>
<p style="text-align: justify;"><strong>Luogo di trattamento dei dati</strong><br /> I trattamenti connessi ai servizi Web su questo sito hanno luogo presso <?php echo $_SESSION["gestore"]; ?> , presso ARUBA BUSINESS srl (ex WIDESTORE srl) Via Gulinelli, 21/a, 44122 Ferrara, da considerarsi corresponsabili del trattamento, e sono curati solo da dipendenti, collaboratori o incaricati al trattamento, oppure da eventuali incaricati di occasionali operazioni di manutenzione. Nessun dato derivante dal servizio Web viene comunicato o diffuso. I dati personali forniti dagli utenti che inoltrano richieste di invio di materiale informativo sono utilizzati al solo fine di eseguire il servizio o la prestazione richiesta e sono comunicati a terzi nel caso in cui ciò sia a tal fine necessario salvo (vedi capitolo "facoltatività del conferimento dei dati").</p>
<p style="text-align: justify;"><strong>Finalità del trattamento</strong><br /> I dati raccolti vengono trattati nel rispetto del GDPR, al fine di svolgere il servizio richiesto dall'utente e adempiere all'obbligazione assunta nei confronti del medesimo, come, ad esempio, rispondere alle richieste di informazioni oppure alla richiesta di invio della newsletter e relativa iscrizione nella mailing list, avente ad oggetto messaggi informativi e comunicazioni commerciali e promozionali relativi all’attività svolta dal Titolare, nel completo rispetto dei principi di liceità e correttezza e delle disposizioni di legge. Tuttavia, a seconda del servizio richiesto e della tipologia del sito web, i dati potrebbero essere utilizzati per attività promozionali oppure per consentire il contatto con altri clienti. In ogni caso, verrà sempre richiesto all'interessato il consenso per ciascun tipo di trattamento dei propri dati.</p>
<p style="text-align: justify;"><strong>TIPI DI DATI TRATTATI</strong></p>
<p style="text-align: justify;"><strong>Dati di Navigazione</strong><br /> I sistemi informatici e le procedure software preposte al funzionamento di questo sito web acquisiscono, nel corso del loro normale esercizio, alcuni dati personali la cui trasmissione è implicita nell'uso dei protocolli di comunicazione di Internet. Si tratta d'informazioni che <span style="text-decoration: underline;">non sono raccolte per essere associate ad interessati identificati</span>, ma che per loro stessa natura potrebbero, attraverso elaborazioni ed associazioni con dati detenuti da terzi, permettere di identificare gli utenti. In questa categoria di dati rientrano gli indirizzi IP o i nomi a dominio dei computer utilizzati dagli utenti che si connettono al sito, gli indirizzi in notazione URI (Uniform Resource Identifier) delle risorse richieste, l'orario della richiesta, il metodo utilizzato nel sottoporre la richiesta al server, la dimensione del file ottenuto in risposta, il codice numerico indicante lo stato della risposta data dal server (buon fine, errore, ecc.) ed altri parametri relativi al sistema operativo e all'ambiente informatico dell'utente. Questi dati sono utilizzati al solo fine di ricavare informazioni statistiche anonime sull'uso del sito e per controllarne il corretto funzionamento e vengono cancellati immediatamente dopo l'elaborazione. I dati potrebbero essere utilizzati per l'accertamento di responsabilità in caso di ipotetici reati informatici ai danni del sito.</p>
<p style="text-align: justify;"><strong>Dati forniti volontariamente dall'utente</strong><br /> L'invio facoltativo, esplicito e volontario di posta elettronica agli indirizzi indicati su questo sito comporta la successiva acquisizione dell'indirizzo del mittente, necessario per rispondere alle richieste, nonché degli eventuali altri dati personali inseriti nella missiva.<br />Specifiche informative di sintesi verranno progressivamente riportate o visualizzate nelle pagine del sito predisposte per particolari servizi a richiesta.</p>
<p style="text-align: justify;"><strong>Facoltatività del conferimento dei dati</strong><br /> A parte quanto specificato per i dati di navigazione, l'utente è libero di fornire i dati personali riportati nei moduli di richiesta o comunque indicati in contatti per sollecitare l'invio di materiale informativo o di altre comunicazioni. Il loro mancato conferimento può comportare l'impossibilità di ottenere quanto richiesto. Per completezza va ricordato che in alcuni casi (non oggetto dell'ordinaria gestione di questo sito) l'Autorità può richiedere notizie e informazioni ai sensi dell'art. 157 del D.Lgs. n. 196/2003, ai fini del controllo sul trattamento dei dati personali. In questi casi la risposta è obbligatoria a pena di sanzione amministrativa. 'User name' e 'password': nel caso in cui per l'accesso a sezioni riservate del sito vi venga richiesto di scegliere uno 'user name' ed una 'password', sarà vostra responsabilità mantenere tali dati riservati e comunicarci immediatamente il loro utilizzo da persone non autorizzate.</p>
<p style="text-align: justify;"><strong>Modalità del trattamento</strong><br /> I dati personali sono trattati con strumenti automatizzati per il tempo strettamente necessario a conseguire gli scopi per cui sono stati raccolti. Specifiche ed adeguate misure di sicurezza sono adottate per prevenire la perdita dei dati, usi illeciti o non corretti ed accessi non autorizzati in ottemperanza agli obblighi di adeguamento a misure minime di sicurezza. La informiamo che, per fornire un servizio completo il nostro portale contiene link ad altri siti web, non gestiti da noi. Non siamo responsabili di errori, contenuti, cookies, pubblicazioni di contenuto morale illecito, pubblicità, banner o files non conformi alle disposizioni normative vigenti e del rispetto della normativa Privacy da parte di siti da noi gestiti a cui si fa riferimento. Per migliorare il servizio offerto è gradita una immediata segnalazione di malfunzionamenti, abusi o suggerimenti all’indirizzo di posta elettronica: <?php echo $_SESSION["pemail"]; ?> .</p>
<p style="text-align: justify;"><strong>Diritti degli interessati</strong><br /> I soggetti cui si riferiscono i dati personali hanno il diritto in qualunque momento l'accesso ai propri dati personali per ottenere la conferma dell'esistenza o meno dei medesimi dati e di conoscerne il contenuto e l'origine, verificarne l'esattezza, chiederne l'integrazione o l'aggiornamento, oppure la rettificazione (art. 13 Reg. UE 679/2016).</p>
<ol style="text-align: justify;">
	<li>L'interessato ha altresì il diritto di opporsi al trattamento dei dati per motivi legittimi e, in particolare, per quelli indicati all'art. 21 del GDPR, di chiedere la limitazione dei dati nonché la loro portabilità. L'interessato può chiedere la cancellazione dei propri dati se sussiste uno dei motivi indicati dall'art. 17 del Reg. UE 679/16, che si riporta integralmente:<ol style="list-style-type: lower-alpha;">
			<li>i dati personali non sono più necessari rispetto alle finalità per le quali sono stati raccolti o altrimenti trattati;</li>
			<li>l'interessato revoca il consenso su cui si basa il trattamento conformemente all'articolo 6, paragrafo 1, lettera a), o all'articolo 9, paragrafo 2, lettera a), e se non sussiste altro fondamento giuridico per il trattamento;</li>
			<li>l'interessato si oppone al trattamento ai sensi dell'articolo 21, paragrafo 1, e non sussiste alcun motivo legittimo prevalente per procedere al trattamento, oppure si oppone al trattamento ai sensi dell'articolo 21, paragrafo 2;</li>
			<li>i dati personali sono stati trattati illecitamente;</li>
			<li>i dati personali devono essere cancellati per adempiere un obbligo legale previsto dal diritto dell'Unione o dello Stato membro cui è soggetto il titolare del trattamento;</li>
			<li>i dati personali sono stati raccolti relativamente all'offerta di servizi della società dell'informazione di cui all'articolo 8, paragrafo 1.</li>
		</ol>
	</li>
	<li>tenendo conto della tecnologia disponibile e dei costi di attuazione adotta le misure ragionevoli, anche tecniche, per informare i titolari del trattamento che stanno trattando i dati personali della richiesta dell'interessato di cancellare qualsiasi link, copia o riproduzione dei suoi dati personali.</li>
	<li>I paragrafi 1 e 2 non si applicano nella misura in cui il trattamento sia necessario:<ol style="list-style-type: lower-alpha;">
			<li>per l'esercizio del diritto alla libertà di espressione e di informazione;</li>
			<li>per l'adempimento di un obbligo legale che richieda il trattamento previsto dal diritto dell'Unione o dello Stato membro cui è soggetto il titolare del trattamento o per l'esecuzione di un compito svolto nel pubblico interesse oppure nell'esercizio di pubblici poteri di cui è investito il titolare del trattamento;</li>
			<li>per motivi di interesse pubblico nel settore della sanità pubblica in conformità dell'articolo 9, paragrafo 2, lettere h) e i), e dell'articolo 9, paragrafo 3;</li>
			<li>a fini di archiviazione nel pubblico interesse, di ricerca scientifica o storica o a fini statistici conformemente all'articolo 89, paragrafo 1, nella misura in cui il diritto di cui al paragrafo 1 rischi di rendere impossibile o di pregiudicare gravemente il conseguimento degli obiettivi di tale trattamento; o</li>
			<li>per l'accertamento, l'esercizio o la difesa di un diritto in sede giudiziaria.</li>
		</ol>
	</li>
</ol>
<p style="text-align: justify;">L'interessato potrà revocare il consenso qualsiasi momento se esso sia stato prestato per una o più specifiche finalità, senza pregiudicare la liceità del trattamento basata sul consenso che aveva espresso prima della revoca.</p>
<p style="text-align: justify;">L'interessato, inoltre, nel caso di violazione dei propri dati personali, potrà proporre reclamo alla competente autorità di controllo.</p>
<p style="text-align: justify;">Le richieste vanno rivolte a <?php echo $_SESSION["nome"]; ?>, <?php echo $_SESSION["indirizzo"]; ?> oppure all'indirizzo e-mail: <?php echo $_SESSION["pemail"]; ?> .</p>
<p style="text-align: justify;"><strong>Modifiche al presente documento</strong><br /> <?php echo $_SESSION["nome"]; ?> si riserva il diritto di aggiornare la presente Privacy Policy per adeguarla al diritto sopravveniente, nonché tenendo in debita considerazione i suggerimenti trasmessi da dipendenti, clienti, collaboratori ed utenti. In caso di modifiche alla presente Privacy Policy da parte di <?php echo $_SESSION["nome"]; ?>, verrà visualizzata la parola 'aggiornamento' accanto al collegamento dell'Informativa sulla privacy nella pagina principale di privacy nella pagina principale di <?php echo $_SESSION["sito"]; ?>.</p>
<p style="text-align: justify;">In caso di modifiche sostanziali alla Privacy Policy <?php echo $_SESSION["nome"]; ?> pubblicherà in maniera visibile tali modifiche.</p>